name: Deploy Documentation

on:
  push:
    branches:
      - main  # Replace with your default branch if it's not 'main'
      - develop 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3  # Update to v3
        with:
          node-version: '20'

      - name: Set up Python
        uses: actions/setup-python@v4  # Update to v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx
          pip install sphinxcontrib-mermaid
          pip install -e src/.  # Installs the package in editable mode from the root

      - name: Build Documentation
        run: |
          cd docs
          make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./docs/build/html
